
name: 'Hello World'
description: 'Greet someone'
inputs:
  dir:
    description: 'Directory'
    required: true
runs:
  using: "composite"
  steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Create dependencies layer for python
        run: |
          function_name=$(basename $dir)
          LAYER_NAME=PYTHON-DEP-${function_name}

          mkdir -p $function_name-deps/python

          python -m pip install \
            --platform manylinux2014_x86_64 \
            --only-binary=:all: \
            --target ./$function_name-deps/python \
            -r $dir/requirements.txt \
            --no-user

          # Create a zip file containing the layer content
          cd $function_name-deps
          zip -r layer.zip .

          # Publish the layer to AWS Lambda
          aws lambda publish-layer-version \
            --layer-name $LAYER_NAME \
            --description "Python dependencies for $dir" \
            --zip-file fileb://layer.zip
          
          # Get all versions of the Lambda layer
          LAYER_VERSIONS=$(aws lambda list-layer-versions \
            --layer-name $LAYER_NAME \
            --query 'LayerVersions[*].Version')

          # Sort versions in descending order
          SORTED_VERSIONS=($(echo $LAYER_VERSIONS | tr -d '[],' | tr ' ' '\n' | sort -nr))

          # Retain the latest 5 versions and delete the rest
          for version in "${SORTED_VERSIONS[@]:5}"; do
              echo "Deleting Lambda layer version: $version"
              aws lambda delete-layer-version \
                --layer-name $LAYER_NAME \
                --version-number $version
          done
        env:
          dir: ${{ inputs.dir }}