
name: 'Hello World'
description: 'Greet someone'
inputs:
  dir:
    description: 'Directory'
    required: true
runs:
  using: "composite"
  steps:
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: npm install and build
        run: |
          cd $dir
          npm install
          npm run build --if-present
        env:
          CI: true
          dir: ${{ inputs.dir }}