name: 'Node build'
description: 'Node build'
inputs:
  dir:
    description: 'Directory'
    required: true
  runtime:
    description: 'runtime'
    required: true
runs:
  using: "composite"
  steps:
      - name: Get node version
        id: node_version
        run: |
          # Replace substring using sed
          node_version=$(echo "${{inputs.runtime}}" | sed 's/nodejs//')
          
          # Print the updated string
          echo "node_version=$node_version" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Use Node.js ${{steps.node_version.outputs.node_version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{steps.node_version.outputs.node_version}}

      - name: npm install and build
        run: |
          cd $dir
          npm install
          npm run build --if-present
        env:
          CI: "true"
          dir: ${{ inputs.dir }}
        shell: bash