name: 'Node build'
description: 'Node build'
inputs:
  dir:
    description: 'Directory'
    required: true
  runtime:
    description: 'runtime'
    required: true
runs:
  using: "composite"
  steps:
      - name: Extract node version
        id: node_version
        uses: ./.github/actions/replace
        with:
          body: ${{ inputs.runtime }}
          string1: "nodejs"
          string2: ""

      - name: Use Node.js ${{steps.node_version.outputs.value}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{steps.node_version.outputs.value}}

      - name: npm install and build
        run: |
          cd $dir
          npm install
          npm run build --if-present
        env:
          CI: "true"
          dir: ${{ inputs.dir }}
        shell: bash