
name: 'Hello World'
description: 'Greet someone'
inputs:
  dir:
    description: 'Directory'
    required: true
  ecr_repo:
    description: 'ECR Repo URL'
    required: true
runs:
  using: "composite"
  steps:
      - name: Build Docker image
        run: | 
          cd $dir
          docker build -t my-lambda-function .
        env:
          dir: ${{inputs.dir}}
        shell: bash
        
      - name: Log in to Amazon ECR
        run: aws ecr get-login-password | docker login --username AWS --password-stdin ${{ inputs.ecr_repo }}
        shell: bash
        
      - name: Tag Docker image
        run: docker tag my-lambda-function:latest ${{ inputs.ecr_repo }}/my-lambda-function:latest
        shell: bash
        
      - name: Push Docker image to Amazon ECR
        run: docker push ${{ inputs.ecr_repo }}/my-lambda-function:latest
        shell: bash
        
      - name: Deploy Lambda function
        run: |
          function_name=$(basename $dir)
          # Check if the Lambda function already exists
          if aws lambda get-function --function-name $function_name &> /dev/null; then
              # Function exists, update the function image
              aws lambda update-function-code \
                  --function-name $function_name \
                  --image-uri "${{ inputs.ecr_repo }}/my-lambda-function:latest"
          else
              # Function doesn't exist, create a new one
              if aws iam get-role --role-name ${function_name}-role &> /dev/null; then
                role_arn=$(aws iam get-role --role-name ${function_name}-role --query 'Role.Arn' --output text)
              else
                # Create a new IAM role for the Lambda function
                role_arn=$(aws iam create-role --role-name ${function_name}-role --assume-role-policy-document '{"Version": "2012-10-17","Statement": [{"Effect": "Allow","Principal": {"Service": "lambda.amazonaws.com"},"Action": "sts:AssumeRole"}]}' --query 'Role.Arn' --output text)
                
                # Attach basic Lambda execution policy to the new role
                aws iam attach-role-policy --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole --role-name ${function_name}-role
                aws iam attach-role-policy --policy-arn arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess --role-name ${function_name}-role

                # Role attachment takes time
                sleep 30
              fi
              aws lambda create-function \
                --function-name $function_name \
                --package-type Image \
                --code ImageUri=${{ inputs.ecr_repo }}/my-lambda-function:latest \
                --role $role_arn
        shell: bash
        env:
          dir: ${{inputs.dir}}
        
      - name: Clean up
        run: |
          docker logout ${{ inputs.ecr_repo }}
          docker rmi my-lambda-function:latest
        shell: bash