name: deploy to lambda
on: [push]
jobs:
  get-folders:
    name: Get the lambda folders
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.folder-fetcher.outputs.folders }}
    steps:
      - uses: actions/checkout@v1
      - name: get all folders
        id: folder-fetcher
        run: |
          var1=$(find lambdas -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | jq -R -s -c 'split("\n")[:-1]')
          echo "folders=$var1" >> "$GITHUB_OUTPUT"
  deploy_source:
    name: build and deploy lambda
    needs: get-folders
    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x]
        manifest: ${{ fromJson(needs.get-folders.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          cd lambdas/${{matrix.manifest}}
          npm install
          npm run build --if-present
        env:
          CI: true
      - name: zip
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r -j ./bundle.zip ./lambdas/${{matrix.manifest}}/*
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-north-1
          function_name: ${{matrix.manifest}}
          zip_file: bundle.zip
